name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (version can be adjusted based on your project's needs)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # or '18', depending on your Node version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the tests
      - name: Run tests
        run: npm run test
